CREATE DATABASE BUS_RESERVATION;
USE BUS_RESERVATION;
CREATE TABLE BUS_STATION(
STATION_CODE VARCHAR(25),
STATION_NAME VARCHAR(100) NOT NULL,
LOCATION VARCHAR(50) NOT NULL,
CITY VARCHAR(50) NOT NULL,
STATE VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50) NOT NULL,
ZIP NUMERIC NOT NULL,
CONSTRAINT BUS_STATION_PK PRIMARY KEY (STATION_CODE)
);
CREATE TABLE BUS_COMPANY(
COMPANY_ID VARCHAR(50) ,
COMPANY_NAME VARCHAR(100) NOT NULL,
CONSTRAINT COMPANY_PK PRIMARY KEY (COMPANY_ID)
);
CREATE TABLE BUS(
BUS_NO VARCHAR(25) ,
SEATING_CAPACITY NUMERIC NOT NULL,
COMPANY VARCHAR(50) NOT NULL,
CONSTRAINT BUS_PK PRIMARY KEY (BUS_NO),
CONSTRAINT BUS_COMPANY_FK FOREIGN KEY (COMPANY)
REFERENCES BUS_COMPANY(COMPANY_ID)
);
CREATE TABLE BUS_STATION_ACCESS(
BUS_STATION VARCHAR(25) NOT NULL,
BUS VARCHAR(25) NOT NULL,
CONSTRAINT ACCESS_PK PRIMARY KEY (BUS_STATION,BUS),
CONSTRAINT ACCESS_PORT_FK FOREIGN KEY (BUS_STATION)
REFERENCES BUS_STATION(STATION_CODE)
ON DELETE CASCADE,
CONSTRAINT ACCESS_BUS_FK FOREIGN KEY (BUS)
REFERENCES BUS(BUS_NO)
ON DELETE CASCADE
);
CREATE TABLE SEAT(
BUS VARCHAR(25) NOT NULL,
SEAT_NO VARCHAR(5) NOT NULL,
STATUS VARCHAR(10) DEFAULT 'TRUE',
LOCATION VARCHAR(25) NOT NULL,
CLASS VARCHAR(25) NOT NULL,
CONSTRAINT SEAT_PK PRIMARY KEY (BUS,SEAT_NO),
CONSTRAINT SEAT_BUS_FK FOREIGN KEY (BUS)
REFERENCES BUS(BUS_NO)
ON DELETE CASCADE
);
CREATE TABLE USER(
EMAIL VARCHAR(25) ,
FNAME VARCHAR(25) NOT NULL,
LNAME VARCHAR(25) NOT NULL,
PHONE NUMERIC ,
TYPE_OF_USER VARCHAR(25) NOT NULL,
CONSTRAINT USER_PK PRIMARY KEY (EMAIL)
);

CREATE TABLE BUS_TRIP(
PNR VARCHAR(15) ,
NO_OF_PASSENGERS NUMERIC NOT NULL,
ARRIVAL_STATION VARCHAR(25) NOT NULL,
ARRIVAL_TIME DATE NOT NULL,
DEPART_STATION VARCHAR(25) NOT NULL,
DEPART_TIME DATE NOT NULL,
USER_EMAIL VARCHAR(25) ,
CONSTRAINT BUS_TRIP_PK PRIMARY KEY
(PNR),
CONSTRAINT BUS_TRIP_USER_FK FOREIGN KEY
(USER_EMAIL) REFERENCES USER(EMAIL)
ON DELETE SET NULL
);
CREATE TABLE FARE(
PNR VARCHAR(15) ,
FINAL_AMOUNT DECIMAL(9,2) NOT NULL,
AMOUNT DECIMAL(9,2) NOT NULL,
CURRENCY VARCHAR(5) NOT NULL,
DISCOUNT DECIMAL(4,2) NOT NULL,
TAX DECIMAL(5,2) NOT NULL,
CONSTRAINT FARE_PK PRIMARY KEY (PNR),
CONSTRAINT FARE_FLT_TRIP_FK FOREIGN KEY
(PNR) REFERENCES BUS_TRIP(PNR)
ON DELETE CASCADE
);
CREATE TABLE PASSENGER(
ID NUMERIC,
PHONE INTEGER,
FNAME VARCHAR(25) NOT NULL,
LNAME VARCHAR(25) NOT NULL,
CONSTRAINT PASSENGER_PK PRIMARY KEY (ID)
);
CREATE TABLE TRAVELLER_ITINERARY(
BUS_JOURNEY VARCHAR(15) NOT NULL,
ID VARCHAR(15),
SEAT_NO VARCHAR(5),
BUS VARCHAR(25),
CONSTRAINT TRAVELLER_PKK PRIMARY KEY
(BUS_JOURNEY,SEAT_NO,BUS),
CONSTRAINT TRVLR_BUS_TRIP_FK FOREIGN KEY (BUS_JOURNEY)
REFERENCES BUS_TRIP(PNR)
ON DELETE CASCADE,
CONSTRAINT TRVLR_SEAT_FK FOREIGN KEY(BUS,SEAT_NO)
REFERENCES SEAT(BUS,SEAT_NO)
);
CREATE TABLE TRAVEL(
TRAVEL_ID VARCHAR(15) ,
DISTANCE DECIMAL(7,2) NOT NULL,
BASE_FARE DECIMAL(9,2) NOT NULL,
BUS VARCHAR(25) NOT NULL,
ARRIVAL_BUS VARCHAR(25) NOT NULL,
ARRIVAL_TIME DATE NOT NULL,
DEPART_BUS VARCHAR(25) NOT NULL,
DEPART_TIME DATE NOT NULL,
CONSTRAINT HOP_PK PRIMARY KEY (TRAVEL_ID),
CONSTRAINT HOP_BUS_FK FOREIGN KEY (BUS)
REFERENCES BUS(BUS_NO),
CONSTRAINT HOP_ARVL_STN_FK FOREIGN KEY(ARRIVAL_BUS)
REFERENCES BUS_STATION(STATION_CODE),
CONSTRAINT HOP_DRPT_BUS_FK FOREIGN KEY(DEPART_BUS)
REFERENCES BUS_STATION(STATION_CODE)
);
CREATE TABLE HAS(
TRAVEL VARCHAR(25) NOT NULL,
BUS_TRIP VARCHAR(15) NOT NULL,
CONSTRAINT HP_HAS_BUS_PK PRIMARY KEY
(TRAVEL,BUS_TRIP),
CONSTRAINT HOP_HAS_FK FOREIGN KEY (TRAVEL) REFERENCES
TRAVEL(TRAVEL_ID),
CONSTRAINT BT_HAS_FK FOREIGN KEY(BUS_TRIP)
REFERENCES BUS_TRIP(PNR)
ON DELETE CASCADE
);
ALTER TABLE TRAVELLER_ITINERARY
MODIFY ID NUMERIC;
ALTER TABLE TRAVELLER_ITINERARY
ADD CONSTRAINT FK_ID
FOREIGN KEY (ID) REFERENCES PASSENGER(ID);
ALTER TABLE USER
ADD constraint sd_chk CHECK (LENGTH(PHONE) = 10);
ALTER TABLE SEAT
ADD CONSTRAINT SD1_CHK CHECK(CLASS='GENERAL' OR CLASS='AC' OR CLASS='SLEEPER');
ALTER TABLE PASSENGER
MODIFY PHONE NUMERIC;
ALTER TABLE travel DROP ARRIVAL_TIME;
ALTER TABLE travel DROP depart_time;
Drop table bus_audit1;

UPDATE `bus_reservation`.`fare` SET `TAX` = '90' WHERE (`PNR` = 'i17dec');

UPDATE `bus_reservation`.`travel` SET `base_fare` = '499' WHERE (`travel_id` = 'A3');